export const GET_ROOMS_REQUEST = 'GET_ROOMS_REQUEST';
export const GET_ROOMS_SUCCESS = 'GET_ROOMS_SUCCESS';
export const GET_ROOMS_FAILED = 'GET_ROOMS_FAILED';
export const SELECT_ACTIVE_ROOM = 'SELECT_ACTIVE_ROOM';
export const LIST_MESSAGE_REQUEST = 'LIST_MESSAGE_REQUEST';
export const LIST_MESSAGE_SUCCESS = 'LIST_MESSAGE_SUCCESS';
export const LIST_MESSAGE_FAILED = 'LIST_MESSAGE_FAILED';
